from typing import NamedTuple, Optional
import random
import sqlite3
import time


class Metadata(NamedTuple):
    id:                         Optional[int] = None
    number:                     Optional[int] = None
    group:                      Optional[int] = None
    min_image_index:            Optional[int] = None
    max_image_index:            Optional[int] = None
    grayscale:                  Optional[int] = None
    grayscale_rows:             Optional[int] = None
    grayscale_cols:             Optional[int] = None
    is_used:                    Optional[int] = None
    is_used_rows:               Optional[int] = None
    is_used_cols:               Optional[int] = None
    is_nobirdlikely:            Optional[int] = None
    is_nobirdlikely_rows:       Optional[int] = None
    is_nobirdlikely_cols:       Optional[int] = None
    is_bird:                    Optional[int] = None
    is_bird_rows:               Optional[int] = None
    is_bird_cols:               Optional[int] = None
    special_name:               Optional[int] = None
    special_name_rows:          Optional[int] = None
    special_name_cols:          Optional[int] = None
    is_present:                 Optional[int] = None
    is_present_rows:            Optional[int] = None
    is_present_cols:            Optional[int] = None


class Database:
    def __init__(self, path: str):
        self._path = path
        self._conn = None

    def __enter__(self):
        self._conn = sqlite3.connect(self._path)
        c = self._conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS metadata (
                id                       INTEGER PRIMARY KEY NOT NULL,
                number                   INTEGER NOT NULL,
                "group"                  INTEGER NOT NULL,
                min_image_index          INTEGER NOT NULL,
                max_image_index          INTEGER NOT NULL,
                grayscale                BLOB NOT NULL,
                grayscale_rows           INTEGER NOT NULL,
                grayscale_cols           INTEGER NOT NULL,
                is_used                  BLOB NOT NULL,
                is_used_rows             INTEGER NOT NULL,
                is_used_cols             INTEGER NOT NULL,
                is_nobirdlikely          BLOB NOT NULL,
                is_nobirdlikely_rows     INTEGER NOT NULL,
                is_nobirdlikely_cols     INTEGER NOT NULL,
                is_bird                  BLOB NOT NULL,
                is_bird_rows             INTEGER NOT NULL,
                is_bird_cols             INTEGER NOT NULL,
                special_name             BLOB NOT NULL,
                special_name_rows        INTEGER NOT NULL,
                special_name_cols        INTEGER NOT NULL,
                is_present               BLOB NOT NULL,
                is_present_rows          INTEGER NOT NULL,
                is_present_cols          INTEGER NOT NULL
            )
        ''')
        self._conn.commit()
        return self

    def __exit__(self, type, value, traceback):
        self._conn.commit()
        self._conn.close()

    def add(self, m: Metadata) -> Metadata:
        c = self._conn.cursor()
        # Insert everything but the id, it's generated by the database.
        c.execute('''
            INSERT INTO metadata (
                number,
                "group",
                min_image_index,
                max_image_index,
                grayscale,
                grayscale_rows,
                grayscale_cols,
                is_used,
                is_used_rows,
                is_used_cols,
                is_nobirdlikely,
                is_nobirdlikely_rows,
                is_nobirdlikely_cols,
                is_bird,
                is_bird_rows,
                is_bird_cols,
                special_name,
                special_name_rows,
                special_name_cols,
                is_present,
                is_present_rows,
                is_present_cols
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', m[1:])
        return self.get(c.lastrowid)

    def get(self, id: int) -> Metadata:
        c = self._conn.cursor()
        c.execute('''
            SELECT
                id,
                number,
                "group",
                min_image_index,
                max_image_index,
                grayscale,
                grayscale_rows,
                grayscale_cols,
                is_used,
                is_used_rows,
                is_used_cols,
                is_nobirdlikely,
                is_nobirdlikely_rows,
                is_nobirdlikely_cols,
                is_bird,
                is_bird_rows,
                is_bird_cols,
                special_name,
                special_name_rows,
                special_name_cols,
                is_present,
                is_present_rows,
                is_present_cols
            FROM
                metadata
            WHERE
                id = ?
        ''', (id,))
        return Metadata(*c.fetchone())

    def update(self, id: int, m: Metadata) -> Metadata:
        c = self._conn.cursor()
        # Dynamically build sql query to do an update.
        sql = '''UPDATE metadata SET {} WHERE id = ?'''.format(",".join([
            f'{k}={v}'
            for k, v
            in m._asdict().items()
            if k != 'id' and v is not None  # Don't update the primary key.
        ]))
        c.execute(sql, (id,))
        return self.get(c.lastrowid)

    def delete(self, id: int) -> None:
        c = self._conn.cursor()
        c.execute('''DELETE FROM metadata WHERE id = ?''', (id,))
